language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t FIL1994/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true FIL1994/docker-react npm run test -- --coverage
